name: app

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/build-and-push-docker-images#path-context
# https://docs.docker.com/build/ci/github-actions/examples/

on:
  push:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:

jobs:
  build-goldendict-app-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          docker run -i --rm --privileged --workdir=/src -v /artifact:/artifact ghcr.io/seyoungsong/goldendict /bin/bash < .docker/goldendict/build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoldenDict.AppImage
          path: /artifact/*
