name: app

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/build-and-push-docker-images#path-context
# https://docs.docker.com/build/ci/github-actions/examples/

on:
  push:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:

jobs:
  build-goldendict-app-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker run --interactive --privileged -v /artifact:/artifact ghcr.io/seyoungsong/goldendict /bin/bash < .docker/goldendict/build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoldenDict.AppImage
          path: /artifact/GoldenDict*.AppImage # GoldenDict-5034348-x86_64.AppImage
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "GoldenDict Linux AppImage (Continuous Build)"
          tag_name: GoldenDict-Linux
          files: /artifact/GoldenDict*.AppImage
  test-build-neko-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: neko
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (base)
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: neko
          file: .docker/neko/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:base
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:base
      - name: Build and push (chromium)
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:base
          context: .docker/neko/chromium
          file: .docker/neko/chromium/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:chromium
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:chromium
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
