name: macos

# From: https://github.com/xiaoyifang/goldendict/blob/staged/.github/workflows/macos-6.x.yml
#       https://github.com/xiaoyifang/goldendict/blob/staged/.github/workflows/macos-PR-check.yml

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-11, macos-12] # https://github.com/actions/runner-images/tree/main/images/macos
        qt_ver: [5.15.2, 6.4.1] # https://en.wikipedia.org/wiki/Qt_version_history
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout (GoldenDict) # https://github.com/xiaoyifang/goldendict
        uses: actions/checkout@v3
        with:
          repository: xiaoyifang/goldendict
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Qt (Qt5) # https://github.com/jurplel/install-qt-action
        if: ${{ matrix.qt_ver == '5.15.2' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }} # https://github.com/miurahr/aqtinstall
          modules: "qtwebengine"
          setup-python: "false"
      - name: Install Qt (Qt6)
        if: ${{ matrix.qt_ver != '5.15.2' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          modules: "qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtimageformats"
          setup-python: "false"

      - name: Brew
        run: |
          brew uninstall opencc hunspell ffmpeg@5 ffmpeg@4 libtiff xz lzo libogg libvorbis zstd || true
          brew install create-dmg

      - name: Build (Qt5)
        if: ${{ matrix.qt_ver == '5.15.2' }}
        run: |
          qmake CONFIG+=release CONFIG+=zim_support goldendict.pro
          make -j$(nproc)
      - name: Build (Qt6)
        if: ${{ matrix.qt_ver != '5.15.2' }}
        run: |
          qmake CONFIG+=release CONFIG+=zim_support QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64" goldendict.pro
          make -j$(nproc)

      - name: Package
        run: |
          macdeployqt GoldenDict.app -qmldir=. -verbose=1
          codesign --force --deep -s - GoldenDict.app
          otool -L GoldenDict.app/Contents/MacOS/GoldenDict
          otool -L GoldenDict.app/Contents/Frameworks/lib*
          mkdir tmp
          mv GoldenDict.app ./tmp
          create-dmg --volname "GoldenDict Installer" --volicon "icons/macicon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "GoldenDict.app" 200 190 --hide-extension "GoldenDict.app" --app-drop-link 600 185 --skip-jenkins "GoldenDict.dmg" tmp/
