name: macos

# From: https://github.com/xiaoyifang/goldendict/blob/staged/.github/workflows/macos.yml

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - name: Checkout (goldendict)
        uses: actions/checkout@v3
        with:
          repository: goldendict/goldendict # https://github.com/goldendict/goldendict
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 # https://github.com/jurplel/install-qt-action
        with:
          version: "5.5.1"
          modules: "qtwebengine"
          setup-python: "false"
      - name: Build
        run: |
          brew uninstall opencc hunspell ffmpeg@5 ffmpeg@4 libtiff xz lzo libogg libvorbis zstd || true
          qmake CONFIG+=release CONFIG+=no_extra_tiff_handler CONFIG+=zim_support goldendict.pro
          make -j$(nproc)
      - name: Package
        run: |
          brew install create-dmg
          macdeployqt GoldenDict.app -qmldir=. -verbose=1
          codesign --force --deep -s - GoldenDict.app
          otool -L GoldenDict.app/Contents/MacOS/GoldenDict
          otool -L GoldenDict.app/Contents/Frameworks/lib*
          mkdir tmp
          mv GoldenDict.app ./tmp
          create-dmg --volname "GoldenDict Installer" --volicon "icons/macicon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "GoldenDict.app" 200 190 --hide-extension "GoldenDict.app" --app-drop-link 600 185 --skip-jenkins "GoldenDict.dmg" tmp/
